FROM python:3.10-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# set working directory
WORKDIR /application

# add and install requirements
COPY ./requirements.txt /application/requirements.txt

RUN pip install --upgrade pip --no-cache-dir\
    && pip install -r requirements.txt --no-cache-dir


# add ap
COPY . .

RUN apt update && apt install -y netcat && chmod +x ./entrypoint.sh

# run server
ENTRYPOINT ["sh", "./entrypoint.sh"]